# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstagramApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InstagramApp
    pod 'Parse'
    pod 'ParseUI'
    pod 'DateTools'

  target 'InstagramAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstagramAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
